export const SKILL_EMOJI_MAP = {
  HTML5: '🌐',
  CSS3: '🎨',
  'JavaScript (ES6+)': '🟨',
  TypeScript: '🔷',
  'React.js': '⚛️',
  'Next.js': '▲',
  'Tailwind CSS': '💨',
  'Framer Motion': '🎞️',
  'Shadcn UI': '🧩',
  'REST APIs': '🔌',
  JSON: '🧾',
  'Redux Toolkit': '🛠️',
  'React Router': '🧭',
  'Node.js': '🟢',
  'Express.js': '🚂',
  MongoDB: '🍃',
  PostgreSQL: '🐘',
  Git: '🧬',
  GitHub: '🐱',
  Vite: '⚡',
  'VS Code': '🧑‍💻',
  Postman: '📮',
  npm: '📦',
  ESLint: '🧹',
  Prettier: '✨',
  Kount: '🛡️'
};
